#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then
	echo "run: run client and server (open in new terminals)"	
	echo "run client: run client"
	echo "run server : run server"
    exit 2	
fi

LD_LIBRARY_PATH=
cd bin
#valgrind --leak-check=full   --show-leak-kinds=all  ./FantasyWorld
if [ "$1" == "server" ]; then
	./FantasyWorldServer
elif [ "$1" == "client" ]; then
	./FantasyWorldClient	
else
	xterm -e ./FantasyWorldServer &
	xterm -e ./FantasyWorldClient &	
fi






